---
inherit_from: .rubocop_todo.yml
require:
- rubocop-rspec
- rubocop-i18n
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: '2.1'
  Include:
  - "./**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - spec/fixtures/**/*
  - vendor/**/*
Bundler/DuplicatedGem:
  Enabled: false
GetText/DecorateString:
  Enabled: false
GetText/DecorateFunctionMessage:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
RSpec/DescribeSymbol:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/LineLength:
  Exclude:
   - spec/spec_helper.rb
   - spec/spec_helper_acceptance.rb
   - Rakefile
   - Gemfile
Metrics/BlockLength:
  Exclude:
   - spec/**/*_spec.rb
RSpec/ExampleLength:
  Max: 8
Style/ClassAndModuleChildren:
  Enabled: false
Security/Eval:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
Security/JSONLoad:
  Exclude:
    - 'Rakefile'
Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
